#!/usr/bin/env bash
# post-generate-traceability.sh
# Claude Code PostToolUse hook — fires after Edit or Write calls.
# When an artefact generated by /content-model through /test is created
# or modified, this hook reminds Claude to update the requirements
# traceability section in REQUIREMENTS.md.
#
# Input: JSON on stdin with { tool_name, tool_input: { file_path }, tool_output }
# Output: context string on stdout to inject into conversation.

set -euo pipefail

INPUT=$(cat)

FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# Detect artefact types produced by generated commands
IS_GENERATED=false

case "$FILE_PATH" in
  # /content-model artefacts
  *-model*.xml|*content-model*.xml|*-context.xml|*bootstrap-context.xml)
    ARTEFACT_TYPE="content-model"
    IS_GENERATED=true
    ;;
  # /web-scripts artefacts
  *.desc.xml|*.get.js|*.get.java|*.post.js|*.post.java|*.get.json.ftl|*.post.json.ftl)
    ARTEFACT_TYPE="web-script"
    IS_GENERATED=true
    ;;
  # /behaviours artefacts
  *Behaviour.java|*behavior*.xml|*service-context.xml)
    ARTEFACT_TYPE="behaviour"
    IS_GENERATED=true
    ;;
  # /actions artefacts
  *ActionExecuter.java)
    ARTEFACT_TYPE="action"
    IS_GENERATED=true
    ;;
  # /docker-compose artefacts
  *compose.yaml|*Dockerfile)
    ARTEFACT_TYPE="docker-compose"
    IS_GENERATED=true
    ;;
  # /test artefacts
  *IT.java|http-tests/*.sh)
    ARTEFACT_TYPE="test"
    IS_GENERATED=true
    ;;
esac

if [ "$IS_GENERATED" = false ]; then
  exit 0
fi

# Check if REQUIREMENTS.md exists in the project
PROJECT_DIR=$(pwd)
REQ_FILE=""
for candidate in "$PROJECT_DIR/REQUIREMENTS.md" "$PROJECT_DIR/docs/REQUIREMENTS.md"; do
  if [ -f "$candidate" ]; then
    REQ_FILE="$candidate"
    break
  fi
done

if [ -z "$REQ_FILE" ]; then
  # No requirements file yet — nothing to update
  exit 0
fi

echo "Artefact of type '$ARTEFACT_TYPE' was written to $FILE_PATH. Update the traceability section in $REQ_FILE to reflect this generated artefact."
exit 0
